# Generated by Django 5.0.3 on 2024-03-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dropio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drop",
            old_name="drop_data",
            new_name="drop_date",
        ),
        migrations.RenameField(
            model_name="drop",
            old_name="drop_start_data",
            new_name="drop_start_date",
        ),
    ]
