# Generated by Django 5.0.3 on 2024-03-23 11:03

import dirtyfields.dirtyfields
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropio", "0002_rename_drop_data_drop_drop_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DropUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True)),
                (
                    "drop_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, unique=True
                    ),
                ),
                ("drop_code", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.RenameField(
            model_name="drop",
            old_name="drop_start_date",
            new_name="drop_expire_date",
        ),
        migrations.RenameField(
            model_name="drop",
            old_name="drop_end_time",
            new_name="drop_expire_time",
        ),
        migrations.RemoveField(
            model_name="dropuserconnector",
            name="drop_code",
        ),
        migrations.AlterField(
            model_name="dropuserconnector",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="drop",
            name="drop_user",
            field=models.ManyToManyField(
                blank=True, through="dropio.DropUserConnector", to="dropio.dropuser"
            ),
        ),
        migrations.AddField(
            model_name="dropuserconnector",
            name="drop_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dropio.dropuser",
            ),
        ),
    ]
