# Generated by Django 5.0.3 on 2024-03-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropio", "0005_drop_is_drop_stop"),
    ]

    operations = [
        migrations.AddField(
            model_name="drop",
            name="drop_code",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
