# Generated by Django 4.2.7 on 2024-03-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
