# Generated by Django 4.2.7 on 2024-03-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="privacy_policy",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="terms_condition",
            field=models.TextField(blank=True),
        ),
    ]
