# Generated by Django 4.2.7 on 2024-03-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopio", "0002_alter_shop_description_alter_shop_privacy_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shipping_charges",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
