# Generated by Django 5.0.3 on 2024-03-13 14:25

import dirtyfields.dirtyfields
import django.db.models.deletion
import django.utils.timezone
import uuid
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True)),
                (
                    "image",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True,
                        height_field="height",
                        null=True,
                        upload_to="",
                        width_field="width",
                    ),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "ppoi",
                    versatileimagefield.fields.PPOIField(
                        default="0.5x0.5", editable=False, max_length=20
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRIMARY_PRODUCT_IMAGE", "Primary Product Image"),
                            ("SECONDARY_PRODUCT_IMAGE", "Secondary Product Image"),
                            ("ADDITIONAL_PRODUCT_IMAGE", "Additional Product Image"),
                            ("USER_PROFILE", "User Profile"),
                            ("USER_COVER", "User Cover"),
                            ("ADMIN_PROFILE", "Admin Profile"),
                            ("ADMIN_COVER", "Admin Cover"),
                            ("SHOP_PROFILE", "Shop Profile"),
                            ("SHOP_COVER", "Shop Cover"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
        migrations.CreateModel(
            name="MediaRoomConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PRIMARY_PRODUCT_IMAGE", "Primary Product Image"),
                            ("SECONDARY_PRODUCT_IMAGE", "Secondary Product Image"),
                            ("ADDITIONAL_PRODUCT_IMAGE", "Additional Product Image"),
                            ("USER_PROFILE", "User Profile"),
                            ("USER_COVER", "User Cover"),
                            ("ADMIN_PROFILE", "Admin Profile"),
                            ("ADMIN_COVER", "Admin Cover"),
                            ("SHOP_PROFILE", "Shop Profile"),
                            ("SHOP_COVER", "Shop Cover"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "media_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mediaroomio.mediaroom",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, dirtyfields.dirtyfields.DirtyFieldsMixin),
        ),
    ]
