# Generated by Django 4.2.7 on 2024-03-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediaroomio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaroom",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRIMARY_PRODUCT_IMAGE", "Primary Product Image"),
                    ("SECONDARY_PRODUCT_IMAGE", "Secondary Product Image"),
                    ("ADDITIONAL_PRODUCT_IMAGE", "Additional Product Image"),
                    ("USER_PROFILE", "User Profile"),
                    ("USER_COVER", "User Cover"),
                    ("ADMIN_PROFILE", "Admin Profile"),
                    ("ADMIN_COVER", "Admin Cover"),
                    ("SHOP_PROFILE", "Shop Profile"),
                    ("SHOP_COVER", "Shop Cover"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mediaroomconnector",
            name="type",
            field=models.CharField(
                choices=[
                    ("PRIMARY_PRODUCT_IMAGE", "Primary Product Image"),
                    ("SECONDARY_PRODUCT_IMAGE", "Secondary Product Image"),
                    ("ADDITIONAL_PRODUCT_IMAGE", "Additional Product Image"),
                    ("USER_PROFILE", "User Profile"),
                    ("USER_COVER", "User Cover"),
                    ("ADMIN_PROFILE", "Admin Profile"),
                    ("ADMIN_COVER", "Admin Cover"),
                    ("SHOP_PROFILE", "Shop Profile"),
                    ("SHOP_COVER", "Shop Cover"),
                ],
                max_length=50,
            ),
        ),
    ]
