"""
Django settings for projectile project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_DIR = os.path.realpath(os.path.join(BASE_DIR, ".."))
# The directory of the current user ie /home/django a.k.a. ~
HOME_DIR = os.path.realpath(os.path.join(REPO_DIR, ".."))
STATIC_DIR = os.path.realpath(os.path.join(HOME_DIR, "staticfiles"))

MEDIA_DIR = os.path.realpath(os.path.join(HOME_DIR, "emedia"))

STATIC_ROOT = STATIC_DIR
STATIC_URL = "/static/"

MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = "/emedia/"

STATICFILES_DIRS = [os.path.join(REPO_DIR, "assets")]

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8a()e!d$4_tul9$p7v-dg=5h!a7hedax7uu$0zv%t#$dh9qfaf"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "core.apps.CoreConfig",
    "shopio.apps.ShopioConfig",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "productio.apps.ProductioConfig",
    "mediaroomio.apps.MediaroomioConfig",
    # "corsheaders",
    "orderio.apps.OrderioConfig",
    "django_extensions",
    "dropio.apps.DropioConfig",
]

# set base auth user model
AUTH_USER_MODEL = "core.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "projectile.urls"

ENABLE_CORS_HEADERS = True

if ENABLE_CORS_HEADERS:
    INSTALLED_APPS = [
        "corsheaders",
    ] + INSTALLED_APPS
    MIDDLEWARE = [
        "corsheaders.middleware.CorsMiddleware",
    ] + MIDDLEWARE

    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "https://0c4crp42-8000.asse.devtunnels.ms",
    ]
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "https://0c4crp42-8000.asse.devtunnels.ms",
    ]
    CORS_ALLOW_HEADERS = (
        *default_headers,
        "accept",
        "authorization",
        "content-type",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
        "x-domain",
    )
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://\w+\.localhost:3000",
    ]
    CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "projectile.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "ecommerce",
        "USER": "sanoth",
        "PASSWORD": "sanoth",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 40,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
}
SPECTACULAR_SETTINGS = {
    "SCHEMA_PATH_PREFIX": r"/api/v[0-9]",
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STRIPE_PUBLIC_KEY = "pk_test_51OuIewSCsmib4OrofS7pNAOshW9fNW6bSdFBANEN2pKWQCCvMyIh7slwrt987h75DJlw8QGQ15zSKXCoQIji2NNl00tanEJkaG"
STRIPE_PRIVATE_KEY = "sk_test_51OuIewSCsmib4OrowSbl2Rc06oFwv5pqVVHQaPVZQpc3ck0YsKn2rHvfh03NcKAGc4WXPRq6jJMaYHtOrBDr8Xcv00vrDEb3Sn"
STRIPE_WEBHOOK_SECRET = (
    "whsec_bfa983f37e1930f10eb0d7a115cb1ff660242a14a1446052be1ce36fea92db0d"
)

TWILIO_MY_ACCOUNT_SID = "AC4286e8fe4e7b1498f68a5da605cdfea6"
TWILIO_AUTH_TOKEN = "ceaaeb70ea0238b5c1dcff1ec245a913"
MY_TWILIO_NUMBER = "+13232104993"
