# Generated by Django 5.0.3 on 2024-03-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
