# Generated by Django 5.0.3 on 2024-03-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderio", "0002_order_is_ordered_order_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="size",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
