# Generated by Django 5.0.3 on 2024-03-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderio", "0003_orderitems_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
