# Generated by Django 5.0.3 on 2024-03-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderio", "0004_order_address_order_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_shipping_charge",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="order",
            name="user_cart_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("ORDER_PLACED", "Order Placed"),
                    ("PAYMENT_INCOMPLETE", "Payment Incomplete"),
                    ("ON_THE_WAY", "On the way"),
                    ("OUT_FOR_DELIVERY", "Out for delivery"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PAYMENT_INCOMPLETE",
                max_length=50,
            ),
        ),
    ]
