# Generated by Django 5.0.3 on 2024-03-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderio", "0005_order_order_shipping_charge_order_user_cart_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("ORDER_PLACED", "Order Placed"),
                    ("PROCESSING", "Processing"),
                    ("PAYMENT_INCOMPLETE", "Payment Incomplete"),
                    ("ON_THE_WAY", "On the way"),
                    ("OUT_FOR_DELIVERY", "Out for delivery"),
                    ("DELIVERED", "Delivered"),
                ],
                default="PAYMENT_INCOMPLETE",
                max_length=50,
            ),
        ),
    ]
